=== Valocop/java-web-training-Epam/tasks/module3/src/test/resources/medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="medicines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medicine" type="Medicine" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Medicine">
        <xs:sequence>
            <xs:element name="medType" type="Type"/>
            <xs:element name="medVersion" type="Version"/>
            <xs:element name="analogs" type="Analogs"/>
            <xs:element name="pharms" type="Pharms"/>
        </xs:sequence>
        <xs:attribute name="medID" type="xs:long" use="required"/>
        <xs:attribute name="medName" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="Analogs">
        <xs:sequence>
            <xs:element name="analog" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Pharms">
        <xs:sequence>
            <xs:element name="pharm" type="Pharm" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Pharm">
        <xs:sequence>
            <xs:element name="certificate" type="Certificate"/>
            <xs:element name="package" type="Package"/>
            <xs:element name="dosage" type="Dosage"/>
        </xs:sequence>
        <xs:attribute name="pharmID" type="xs:long" use="required"/>
        <xs:attribute name="pharmName" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="Dosage">
        <xs:sequence>
            <xs:element name="dosa">
                <xs:simpleType>
                    <xs:restriction base="xs:double"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="frequency">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Package">
        <xs:sequence>
            <xs:element name="packageType" type="PackageType"/>
            <xs:element name="count">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="value">
                <xs:simpleType>
                    <xs:restriction base="xs:double"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Certificate">
        <xs:sequence>
            <xs:element name="number">
                <xs:simpleType>
                    <xs:restriction base="xs:long"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="issueDate">
                <xs:simpleType>
                    <xs:restriction base="xs:date"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="shelfDate">
                <xs:simpleType>
                    <xs:restriction base="xs:date"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="registrOrganization">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PackageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BOX"/>
            <xs:enumeration value="BANK"/>
            <xs:enumeration value="BOTTLE"/>
            <xs:enumeration value="PLATE"/>
            <xs:enumeration value="SACHET"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PAIN_MEDICATION"/>
            <xs:enumeration value="ANTIBIOTIC"/>
            <xs:enumeration value="VITAMIN"/>
            <xs:enumeration value="SEDATIVE"/>
            <xs:enumeration value="VACCINE"/>
            <xs:enumeration value="PSYCHOTROPIC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Version">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PILL"/>
            <xs:enumeration value="CAPSULE"/>
            <xs:enumeration value="POWDER"/>
            <xs:enumeration value="DROPS"/>
            <xs:enumeration value="SYRUP"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Valocop/java-web-training-Epam/tasks/module3/src/test/resources/medicineNotValid.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="medicine.xsd">

    <medicine medID="123423435" medName="Analgin">
        <medType>PAIN_MEDICATION</medType>
        <medVersion>PILL</medVersion>
        <analogs>
            <analog>Andifen</analog>
            <analog>Baralgetas</analog>
        </analogs>
        <pharms>
            <pharm pharmID="21423423" pharmName="Avexima">
                <certificate>
                    <number>3245345342</number>
                    <issueDate>2018-10-10</issueDate>
                    <shelfDate>2020-10-10</shelfDate>
                    <registrOrganization>Avexima</registrOrganization>
                </certificate>
                <package>
                    <packageType>PLATE</packageType>
                    <count>20</count>
                    <value>7.5</value>
                </package>
                <dosage>
                    <dosa>500</dosa>
                    <frequency>2</frequency>
                </dosage>
            </pharm>
            <pharm pharmID="054605465" pharmName="Belmed">
                <certificate>
                    <number>3245345342</number>
                    <issueDate>2019-09-11</issueDate>
                    <shelfDate>2021-11-20</shelfDate>
                    <registrOrganization>Belmed</registrOrganization>
                </certificate>
                <package>
                    <packageType>PLATE</packageType>
                    <count>15</count>
                    <value>6</value>
                </package>
                <dosage>
                    <dosa>500</dosa>
                    <frequency>3</frequency>
                </dosage>
            </pharm>
        </pharms>
    </medicine>

    <medicine medID="345436456" medName="Festal">
        <medType>PAIN_MEDICATION</medType>
        <medVersion>CAPSULE</medVersion>
        <analogs>
            <analog>Pancreatin</analog>
        </analogs>
        <pharms>
            <pharm pharmID="21423423" pharmName="Borismed">
                <certificate>
                    <number>3456789976</number>
                    <issueDate>2017-06-25</issueDate>
                    <shelfDate>2019-07-25</shelfDate>
                    <registrOrganization>Borismed</registrOrganization>
                </certificate>
                <package>
                    <packageType>BANK</packageType>
                    <count>10</count>
                    <value>13.3</value>
                </package>
                <dosage>
                    <dosa>500</dosa>
                    <frequency>3</frequency>
                </dosage>
            </pharm>
        </pharms>
    </medicine>

    <medicine medID="0230492234" medName="Glicin">
        <medType>SEDATIVE</medType>
        <medVersion>PILL</medVersion>
        <analogs>
            <analog>Gromecin</analog>
        </analogs>
        <pharms>
            <pharm pharmID="268678678" pharmName="Evalar">
                <certificate>
                    <number>098765432</number>
                    <issueDate>2017-05-01</issueDate>
                    <shelfDate>2019-05-03</shelfDate>
                    <registrOrganization>Evalar</registrOrganization>
                </certificate>
                <package>
                    <packageType>BOX</packageType>
                    <count>20</count>
                    <value>3.5</value>
                </package>
                <dosage>
                    <dosa>50</dosa>
                    <frequency>3</frequency>
                </dosage>
            </pharm>
        </pharms>
    </medicine>

    <medicine medID="09876543" medName="Coldrex">
        <medType>PAIN_MEDICATION</medType>
        <medVersion>POWDER</medVersion>
        <analogs>
            <analog>Trialgin</analog>
            <analog>Flupomix</analog>
        </analogs>
        <pharms>
            <pharm pharmID="9875456" pharmName="Leckpharm">
                <certificate>
                    <number>456789045</number>
                    <issueDate>2017-05-01</issueDate>
                    <shelfDate>2019-05-03</shelfDate>
                    <registrOrganization>Leckpharm</registrOrganization>
                </certificate>
                <package>
                    <packageType>SACHET</packageType>
                    <count>1</count>
                    <value>2.1</value>
                </package>
                <dosage>
                    <dosa>1000</dosa>
                    <frequency>1</frequency>
                </dosage>
            </pharm>
            <pharm pharmID="06543643" pharmName="Farmland">
                <certificate>
                    <number>97654465</number>
                    <issueDate>2018-05-01</issueDate>
                    <shelfDate>2020-05-03</shelfDate>
                    <registrOrganization>Farmland</registrOrganization>
                </certificate>
                <package>
                    <packageType>SACHET</packageType>
                    <count>10</count>
                    <value>15</value>
                </package>
                <dosage>
                    <dosa>500</dosa>
                    <frequency>2</frequency>
                </dosage>
            </pharm>
        </pharms>
    </medicine>

    <medicine medID="2434234" medName="Vitamin ะก">
        <medType>VITAMIN</medType>
        <medVersion>PILL</medVersion>
        <analogs>
        </analogs>
        <pharms>
            <pharm pharmID="56787654" pharmName="Malkut">
                <certificate>
                    <number>7678976456</number>
                    <issueDate>2017-07-07</issueDate>
                    <shelfDate>2021-05-03</shelfDate>
                    <registrOrganization>Malkut</registrOrganization>
                </certificate>
                <package>
                    <packageType>BOX</packageType>
                    <count>100</count>
                    <value>10.6</value>
                </package>
                <dosage>
                    <dosa>1200</dosa>
                    <frequency>2</frequency>
                </dosage>
            </pharm>
            <pharm pharmID="87654567" pharmName="Solgar Vitamin">
                <certificate>
                    <number>5672345678</number>
                    <issueDate>2018-05-01</issueDate>
                    <shelfDate>2020-05-03</shelfDate>
                    <registrOrganization>Solgar Vitamin</registrOrganization>
                </certificate>
                <package>
                    <packageType>BOX</packageType>
                    <count>50</count>
                    <value>15.5</value>
                </package>
                <dosage>
                    <frequency>1</frequency>
                </dosage>
            </pharm>
        </pharms>
    </medicine>
</medicines>
